### ISSUE TITLE
Fields in fulfillment, ext pledge not showing up in patient changelog

### ISSUE THREAD

**Issue by colinxfleming** [DARIAEngineering/dcaf_case_management#826] opened 2017-01-30 04:47 UTC
Issue description TK -- affects $$ fields, resolved without DCAF.

Should also do this for external pledges

**Comment by mpetazzoni** [comment] 2017-03-06 02:02
I did some investigation on this, but I haven't been able to fully confirm my theory yet. I suspect the root cause here is that the version of `mongoid-history` being used (0.5.0) has incomplete support for keeping the history tracks of embedded model objects, and upgrading to the latest (>= 0.6.0) might help, but may also require changing how the audit trail is kept (by keeping it all under the patient, instead of on patient and its sub-model objects).

The fields that are not showing up are all part of a sub-model/embedded model, for example `pregnancy`: $$ fields, "Resolved without DCAF". I suspect that the history for those doesn't actually get recorded when the edit initially targets the parent object.

**Comment by colinxfleming** [comment] 2017-03-16 22:35
Hey @mpetazzoni , wanted to flag #948 for you, since this has some implications for the work in here (though it doesn't dig us out of the problem entirely, since we'll still need to solve it for the `patient` -> `fulfillment` relationship). Let me know if I can be helpful or provide any context you'd like -- really appreciate your eyes on this.

**Comment by colinxfleming** [comment] 2017-03-16 22:40
This in turn makes me realize that I haven't really done a good job of describing the problem here. So here's a more fleshed out version using the template:

* **What are we trying to do?**
Record all field changes to the information currently stored in patient, pregnancy, fulfillment, or external pledge objects for a patient document.

* **What feature or behavior is this required for?**
Having a very accurate audit trail for patients, so that we can better reason about what their experience in our case management process was like.

* **How could we solve this issue? (Not knowing is okay!)**
@mpetazzoni 's research suggests that a gem upgrade might assist with this; we can also improve it to a degree by the change in #948 , should we go that route.

* **Anything else?**
💯

**Comment by mpetazzoni** [comment] 2017-03-16 22:46
Thanks @colinxfleming, I have a pretty good grasp on what we're trying to do here. Unfortunately the gem update didn't help, so I need to dig deeper into mongoid-history to figure out what's going on.

I have some other changes in the area of the audit log that I'll submit as distinct PRs as well (mostly visual updates).

**Comment by colinxfleming** [comment] 2017-03-16 22:48
Solid @mpetazzoni . Let me know if there's anything I can do to be helpful. Looking forward to seeing the styling PRs.

**Comment by colinxfleming** [comment] 2018-06-03 05:33
Spent ~15m screwing with this tonight and getting it working seems to be nontrivial, still (no big shocker there, thanks to @mpetazzoni 's research in the issue thread on this front). Going to mark this as a future feature for the time being.

**Comment by colinxfleming** [comment] 2021-07-28 03:18
This is also kinda live now that we're off of mongo - we could do something like:

```
class Patient
  def show_all_changes
    all_changes = versions + external_pledges.map { |x| x.versions } + fulfillment.versions + ...
    all_changes.sort_by { |x| x.created_at }
    return all_changes.map(&:shaped_changes)
  end
end
```

to use all relevant papertrail objs associated with a patient. Would also require probably mucking around with the irrelevant fields / exclusive fields etc, but it kinda looks like `shape_changes` is flexible enough to handle whatever obj we throw at it, which is nice.

**Closed** 2022-09-21 04:13 UTC
Labels: future features
